### ISSUE TITLE
[HYP] Unhandled trap from VM 3

### ISSUE THREAD

**Issue by allenkhcheng** [quic/gunyah-hypervisor#14]
Hi,

I encounter a system hang while testing the Gunyah Hypervisor with the Linux VM on the QEMU simulator. 
(Follow the https://github.com/quic/gunyah-hypervisor/blob/develop/docs/test.md)

Any suggestions would be much appreciated. Thanks

[RM] Starting Resource Manager, version: 727cc85 (Tue Dec 21 03:28:12 2021 UTC)
[RM] memparcel_construct sglist:
[RM]  [0]: me:fabfdee110ae6499 phys:40000000 (20000000)
[RM] memparcel_construct ret=0
[RM] create_dtbo: hyp -1 resmem -1
[RM] create_resmem_nodes: memparcel labelled 0 is the base memory at 0x40000000
[RM] init completed
[RM] UART is disabled
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x34004d. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380089. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3a0089. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3a0007. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3c0007. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380007. RAZ
[HYP] Unhandled trap from VM 3, ESR_EL2 = 0x62380405, ELR_EL2 = 0xffffa9bd8b497174

**Comment by quic-cvanscha** [comment]
Unless I've decoded the ESR_EL2 incorrectly, this looks like Linux VM is trying to access an SME system register which is currently unhandled.
Can you try disable SME in the Linux build or disable the SME cpu feature in QEMU?

**Comment by allenkhcheng** [comment]
Hi Carl,

It works when the SME CPU feature in QEMU is disabled. Thanks for your help.
