### ISSUE TITLE
[Q] Run two VMs on  the Gunyah

### ISSUE THREAD

**Issue by allenkhcheng** [quic/gunyah-hypervisor#15]
Following the steps from https://github.com/quic/gunyah-hypervisor/blob/develop/docs/test.md,

I can boot the Gunyah Hypervisor with the Linux VM on the QEMU simulator.

But it seems there is just one rootvm. 

Can we run two VMs on  the Gunyah Hypervisor with the Linux VM on the QEMU simulator now ?

Any suggestions would be much appreciated. Thanks

**Comment by quic-cvanscha** [comment]
Hi Allen, as per limitations mentioned in the docs, the published version does not have the Linux drivers, VMM and RM support needed to dynamically load a secondary VM. We're working on a major set of updates to address this, but I don't have any date to share yet when this will be ready.

**Comment by allenkhcheng** [comment]
Oh ok, thanks for your reply
