### ISSUE TITLE
How to run secondary VM using Gunyah?

### ISSUE THREAD

**Issue by ygnkim** [quic/gunyah-hypervisor#19]
Hi, I have a question similar to #15 

I succeeded in Gunyah's non-docker setup, but only the primary VM seems to be running. 
I found the documentation (https://github.com/quic/gunyah-hypervisor/blob/develop/CHANGELOG.md) suggesting a Linux patch and CrosVM VMM for SVM loading. 

Is there any documentation I can follow to load the secondary VM on Gunyah?
I also wonder if Gunyah can load a secondary VM without CrosVM or AVF. 

Any advice would be appreciated. Thank you.

**Comment by quic-yvasi** [comment]
We just updated with scripts and instructions on how to verify SVM loading. You can give it a try on the code base you already have. The latest version launches SVM, but there is some issue with power off and then restart. As we had verified, the last version of the code base should work with poweroff and relaunch of SVM.
