### ISSUE TITLE
Is that possible run gunyah for raspberry pi ?

### ISSUE THREAD

**Issue by H-H-bin** [quic/gunyah-hypervisor#21]

**Comment by quic-cvanscha** [comment]
Unfortunately, Gunyah supports SoCs with GICv3 or GICv4. Raspberry Pi4 and Pi5 both appear to still have an old GIC-400 (GICv2) and that would require a fair bit of effort to support.

**Comment by H-H-bin** [comment]
Thanks @quic-cvanscha
