### ISSUE TITLE
Where is the definition of trigger_vectors_* function?

### ISSUE THREAD

**Issue by archersmind** [quic/gunyah-hypervisor#28]
Hello gunyah team,

Where is the definition of the trigger_vectors_* function?  For example trigger_vectors_trap_data_abort_el2_event.

Thanks

**Comment by quic-yvasi** [comment]
These will be part of the generated files, like ```hyp/build/qemu/gunyah-rm-qemu/debug/events/src```

Generated code/files glue all the modules with events dispatching appropriately.

**Comment by archersmind** [comment]
> These will be part of the generated files, like `hyp/build/qemu/gunyah-rm-qemu/debug/events/src`
> 
> Generated code/files glue all the modules with events dispatching appropriately.

Thank you for your reply, I'll build the code for the first time.
