### ISSUE TITLE
Running Gunyah on Qualcomm RB5 (QRB5165 SoC)?

### ISSUE THREAD

**Issue by kisg** [quic/gunyah-hypervisor#8]
Hi,

would it be possible to run Gunyah on a Qualcomm RB5? Do you intend to release a configuration to support this?

Thank you,
Gergely

**Comment by quic-yvasi** [comment]
Sorry currently there is no plan to support open source Gunyah on RB5, since it requires a proprietary lib linked to hyp image and need to QCOM signed. We are looking forward to supporting other open platforms in the future.

Thanks
Yug
