### ISSUE TITLE
A prebuilt docker instance would be really nice

### ISSUE THREAD

**Issue by zengtm** [quic/gunyah-hypervisor#9]
I'm teaching a class at UCSD Ext and thinking of using Gunyah for students to play around. 
Some are Windows users and only have WSL - Windows Subsystem for Linux.

We could not get "docker build -f gunyah/Dockerfile -t user:gunyah ."  to complete because the gcc compiler or ninja ran out of memory on WSL.

Is it possible to host a prebuilt docker instance on hub.docker.com?  I found a lot of Android and KVM dockers, but no Gunyah docker there.

**Comment by quic-cvanscha** [comment]
Hi Zeng, This something we will consider. In the mean time if you build a docker feel free to publish it.

**Comment by quic-yvasi** [comment]
Hi Zeng,

Carl was mentioning that if you modify the scripts to limit the builds to single core (-j 1) that might probably alleviate the memory related issue. You can give it a try with latest updates and see if it works for you.
